name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl git

    - name: Setup asdf
      uses: asdf-vm/actions/setup@v3.0.2

    - name: Run starknetup
      run: |
        ./starknetup.sh
        scarb --version
        snforge --version
        universal-sierra-compiler --version
